/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PressReleaseRouteImport } from './routes/press-release'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesXiiScienceRouteImport } from './routes/courses.xii-science'
import { Route as CoursesXiScienceRouteImport } from './routes/courses.xi-science'
import { Route as CoursesXSscCbseRouteImport } from './routes/courses.x-ssc-cbse'
import { Route as CoursesViiiSscCbseRouteImport } from './routes/courses.viii-ssc-cbse'
import { Route as CoursesNeetRouteImport } from './routes/courses.neet'
import { Route as CoursesMhCetRouteImport } from './routes/courses.mh-cet'
import { Route as CoursesIxSscCbseRouteImport } from './routes/courses.ix-ssc-cbse'
import { Route as CoursesIitJeeRouteImport } from './routes/courses.iit-jee'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PressReleaseRoute = PressReleaseRouteImport.update({
  id: '/press-release',
  path: '/press-release',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesXiiScienceRoute = CoursesXiiScienceRouteImport.update({
  id: '/courses/xii-science',
  path: '/courses/xii-science',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesXiScienceRoute = CoursesXiScienceRouteImport.update({
  id: '/courses/xi-science',
  path: '/courses/xi-science',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesXSscCbseRoute = CoursesXSscCbseRouteImport.update({
  id: '/courses/x-ssc-cbse',
  path: '/courses/x-ssc-cbse',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesViiiSscCbseRoute = CoursesViiiSscCbseRouteImport.update({
  id: '/courses/viii-ssc-cbse',
  path: '/courses/viii-ssc-cbse',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesNeetRoute = CoursesNeetRouteImport.update({
  id: '/courses/neet',
  path: '/courses/neet',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesMhCetRoute = CoursesMhCetRouteImport.update({
  id: '/courses/mh-cet',
  path: '/courses/mh-cet',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIxSscCbseRoute = CoursesIxSscCbseRouteImport.update({
  id: '/courses/ix-ssc-cbse',
  path: '/courses/ix-ssc-cbse',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIitJeeRoute = CoursesIitJeeRouteImport.update({
  id: '/courses/iit-jee',
  path: '/courses/iit-jee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/press-release': typeof PressReleaseRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/courses/iit-jee': typeof CoursesIitJeeRoute
  '/courses/ix-ssc-cbse': typeof CoursesIxSscCbseRoute
  '/courses/mh-cet': typeof CoursesMhCetRoute
  '/courses/neet': typeof CoursesNeetRoute
  '/courses/viii-ssc-cbse': typeof CoursesViiiSscCbseRoute
  '/courses/x-ssc-cbse': typeof CoursesXSscCbseRoute
  '/courses/xi-science': typeof CoursesXiScienceRoute
  '/courses/xii-science': typeof CoursesXiiScienceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/press-release': typeof PressReleaseRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/courses/iit-jee': typeof CoursesIitJeeRoute
  '/courses/ix-ssc-cbse': typeof CoursesIxSscCbseRoute
  '/courses/mh-cet': typeof CoursesMhCetRoute
  '/courses/neet': typeof CoursesNeetRoute
  '/courses/viii-ssc-cbse': typeof CoursesViiiSscCbseRoute
  '/courses/x-ssc-cbse': typeof CoursesXSscCbseRoute
  '/courses/xi-science': typeof CoursesXiScienceRoute
  '/courses/xii-science': typeof CoursesXiiScienceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/press-release': typeof PressReleaseRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/videos': typeof VideosRoute
  '/courses/iit-jee': typeof CoursesIitJeeRoute
  '/courses/ix-ssc-cbse': typeof CoursesIxSscCbseRoute
  '/courses/mh-cet': typeof CoursesMhCetRoute
  '/courses/neet': typeof CoursesNeetRoute
  '/courses/viii-ssc-cbse': typeof CoursesViiiSscCbseRoute
  '/courses/x-ssc-cbse': typeof CoursesXSscCbseRoute
  '/courses/xi-science': typeof CoursesXiScienceRoute
  '/courses/xii-science': typeof CoursesXiiScienceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/gallery'
    | '/press-release'
    | '/results'
    | '/sitemap.xml'
    | '/videos'
    | '/courses/iit-jee'
    | '/courses/ix-ssc-cbse'
    | '/courses/mh-cet'
    | '/courses/neet'
    | '/courses/viii-ssc-cbse'
    | '/courses/x-ssc-cbse'
    | '/courses/xi-science'
    | '/courses/xii-science'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/gallery'
    | '/press-release'
    | '/results'
    | '/sitemap.xml'
    | '/videos'
    | '/courses/iit-jee'
    | '/courses/ix-ssc-cbse'
    | '/courses/mh-cet'
    | '/courses/neet'
    | '/courses/viii-ssc-cbse'
    | '/courses/x-ssc-cbse'
    | '/courses/xi-science'
    | '/courses/xii-science'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/gallery'
    | '/press-release'
    | '/results'
    | '/sitemap.xml'
    | '/videos'
    | '/courses/iit-jee'
    | '/courses/ix-ssc-cbse'
    | '/courses/mh-cet'
    | '/courses/neet'
    | '/courses/viii-ssc-cbse'
    | '/courses/x-ssc-cbse'
    | '/courses/xi-science'
    | '/courses/xii-science'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PressReleaseRoute: typeof PressReleaseRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideosRoute: typeof VideosRoute
  CoursesIitJeeRoute: typeof CoursesIitJeeRoute
  CoursesIxSscCbseRoute: typeof CoursesIxSscCbseRoute
  CoursesMhCetRoute: typeof CoursesMhCetRoute
  CoursesNeetRoute: typeof CoursesNeetRoute
  CoursesViiiSscCbseRoute: typeof CoursesViiiSscCbseRoute
  CoursesXSscCbseRoute: typeof CoursesXSscCbseRoute
  CoursesXiScienceRoute: typeof CoursesXiScienceRoute
  CoursesXiiScienceRoute: typeof CoursesXiiScienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-release': {
      id: '/press-release'
      path: '/press-release'
      fullPath: '/press-release'
      preLoaderRoute: typeof PressReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/xii-science': {
      id: '/courses/xii-science'
      path: '/courses/xii-science'
      fullPath: '/courses/xii-science'
      preLoaderRoute: typeof CoursesXiiScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/xi-science': {
      id: '/courses/xi-science'
      path: '/courses/xi-science'
      fullPath: '/courses/xi-science'
      preLoaderRoute: typeof CoursesXiScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/x-ssc-cbse': {
      id: '/courses/x-ssc-cbse'
      path: '/courses/x-ssc-cbse'
      fullPath: '/courses/x-ssc-cbse'
      preLoaderRoute: typeof CoursesXSscCbseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/viii-ssc-cbse': {
      id: '/courses/viii-ssc-cbse'
      path: '/courses/viii-ssc-cbse'
      fullPath: '/courses/viii-ssc-cbse'
      preLoaderRoute: typeof CoursesViiiSscCbseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/neet': {
      id: '/courses/neet'
      path: '/courses/neet'
      fullPath: '/courses/neet'
      preLoaderRoute: typeof CoursesNeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/mh-cet': {
      id: '/courses/mh-cet'
      path: '/courses/mh-cet'
      fullPath: '/courses/mh-cet'
      preLoaderRoute: typeof CoursesMhCetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/ix-ssc-cbse': {
      id: '/courses/ix-ssc-cbse'
      path: '/courses/ix-ssc-cbse'
      fullPath: '/courses/ix-ssc-cbse'
      preLoaderRoute: typeof CoursesIxSscCbseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/iit-jee': {
      id: '/courses/iit-jee'
      path: '/courses/iit-jee'
      fullPath: '/courses/iit-jee'
      preLoaderRoute: typeof CoursesIitJeeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PressReleaseRoute: PressReleaseRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideosRoute: VideosRoute,
  CoursesIitJeeRoute: CoursesIitJeeRoute,
  CoursesIxSscCbseRoute: CoursesIxSscCbseRoute,
  CoursesMhCetRoute: CoursesMhCetRoute,
  CoursesNeetRoute: CoursesNeetRoute,
  CoursesViiiSscCbseRoute: CoursesViiiSscCbseRoute,
  CoursesXSscCbseRoute: CoursesXSscCbseRoute,
  CoursesXiScienceRoute: CoursesXiScienceRoute,
  CoursesXiiScienceRoute: CoursesXiiScienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
